from unittest import TestCase, TestSuite, makeSuite

from mtj.eve.tracker.pos import Tower, TowerResourceBuffer

FUEL_NORMAL = 1
FUEL_REINFORCE = 4

STATE_UNANCHORED = 0
STATE_ANCHORED = 1
STATE_ONLINING = 2
STATE_REINFORCE = 3
STATE_ONLINE = 4


class StructureTestCase(TestCase):
    """
    Unit tests for structures
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def test_0000_base_tower(self):
        tower = Tower(1000001, 12235, 30004608, 40291202, 4,
            1325376000, 1306886400, 498125261)

        self.assertEqual(tower.capacity, 140000)
        self.assertEqual(tower.strontCapacity, 50000)

    def test_1000_failure_celestial_solarsystem_mismatch(self):
        # Celestial must be located within the solar system
        pass


class TowerResourceBufferTestCase(TestCase):
    """
    Test the buffer subclass implementation.
    """

    def setUp(self):
        self.tower = type('DummyTower', (object,), {})
        self.tower.state = STATE_ONLINE

    def test_0000_basic(self):
        fuelbay = TowerResourceBuffer(self.tower, 40, 0, FUEL_NORMAL,
              28000, "Amarr Fuel Block")
        self.assertTrue(fuelbay.isConsumingFuel())
        self.assertTrue(fuelbay.isNormalFuel())
        self.assertFalse(fuelbay.freeze_FuelCheck(0))

        strontbay = TowerResourceBuffer(self.tower, 400, 0, FUEL_REINFORCE,
              9600, "Strontium Clathrates")
        self.assertTrue(strontbay.isConsumingFuel())
        self.assertFalse(strontbay.isNormalFuel())
        self.assertTrue(strontbay.freeze_FuelCheck(0))

    def test_0100_current(self):
        # even though the new clone generated by getCurrent is not used
        # by the tower as a whole, it should still be consistent with
        # expected results
        fuelbay = TowerResourceBuffer(self.tower, 40, 0, FUEL_NORMAL,
              28000, "Amarr Fuel Block")
        fuelbay1 = fuelbay.getCurrent(3600)

        self.assertEqual(fuelbay1.value, 27960)
        self.assertEqual(fuelbay1.tower, self.tower)
        self.assertEqual(fuelbay1.purpose, fuelbay.purpose)
        self.assertEqual(fuelbay1.resourceTypeName, fuelbay.resourceTypeName)
        self.assertEqual(fuelbay1.unitVolume, fuelbay.unitVolume)

        # The actual frozen state is managed in conjunction with the
        # usage of a tower.  A buffer will faithfully deplete stront
        # currently.
        strontbay = TowerResourceBuffer(self.tower, 400, 0, FUEL_REINFORCE,
              9600, "Strontium Clathrates")
        strontbay1 = strontbay.getCurrent(3600)
        self.assertEqual(strontbay1.value, 9200)

    def test_0200_offline(self):
        fuelbay0 = TowerResourceBuffer(self.tower, 40, 0, FUEL_NORMAL,
              28000, "Amarr Fuel Block")
        self.tower.state = STATE_ANCHORED
        self.assertTrue(fuelbay0.freeze_FuelCheck(0))

        # note: offline timestamp will be assumed to be at 3600
        fuelbay1 = fuelbay0.getCurrent(36000)
        fuelbay2 = fuelbay1.getCurrent(39600)

        self.assertEqual(fuelbay1.value, 27600)
        self.assertEqual(fuelbay2.value, 27600)


def test_suite():
    suite = TestSuite()
    suite.addTest(makeSuite(StructureTestCase))
    suite.addTest(makeSuite(TowerResourceBufferTestCase))
    return suite
